spring.application.name=ats-resume-backend

# Server
server.port=8080

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/atsresume}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=true

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${OAUTH2_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth?prompt=select_account

# JWT
jwt.secret=${JWT_SECRET}
#jwt.secret=${JWT_SECRET:atsresumeappsecretkey1234567890abcdefghijklmnopqrstuvwxyz}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Gemini API
gemini.api.url=${GEMINI_API_URL:https://generativelanguage.googleapis.com/v1beta}
gemini.api.key=${GEMINI_API_KEY}
#gemini.api.key=${GEMINI_API_KEY:AQ.Ab8RN6LuQwO_lfvT061oy5j4oa05go90Ds2z64BSiU-L3x2-qg}

# File Upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# CORS
cors.allowed.origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}